env:
  browser: true
  jest: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:vue/recommended"
rules:
  array-bracket-spacing:
    - error
    - never
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
  eol-last:
    - error
    - always
  import/extension:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - double